name: linux
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: (${{ matrix.target }}, ${{ matrix.features }})
    env:
      FEATURES: ${{ matrix.features}}
    strategy:
      matrix:
        target: [
          x86_64-unknown-linux-gnu,
        ]
        features: [default, atomic]

    steps:
    - name: checkout
      uses: actions/checkout@v3

      # Run build
    - name: install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none
        rustup target add ${{ matrix.target }}

    - name: Build and Test
      run: ./ci/build_and_test.sh